# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
