# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170110_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
