# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170110_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='completedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='startedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
