# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170115_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
