# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20170115_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'View Project'),)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_task', 'View Task'),)},
        ),
    ]
